USE [master]
GO

/****** Object:  Database [compra]    Script Date: 03/11/2020 17:34:00 ******/
DROP DATABASE [compra]
GO

/****** Object:  Database [compra]    Script Date: 03/11/2020 17:34:00 ******/
CREATE DATABASE [compra]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'compra', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\compra.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'compra_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\compra_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [compra].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [compra] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [compra] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [compra] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [compra] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [compra] SET ARITHABORT OFF 
GO

ALTER DATABASE [compra] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [compra] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [compra] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [compra] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [compra] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [compra] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [compra] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [compra] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [compra] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [compra] SET  DISABLE_BROKER 
GO

ALTER DATABASE [compra] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [compra] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [compra] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [compra] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [compra] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [compra] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [compra] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [compra] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [compra] SET  MULTI_USER 
GO

ALTER DATABASE [compra] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [compra] SET DB_CHAINING OFF 
GO

ALTER DATABASE [compra] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [compra] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [compra] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [compra] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [compra] SET QUERY_STORE = OFF
GO

ALTER DATABASE [compra] SET  READ_WRITE 
GO

